#!/usr/bin/env python3
"""Generate src/silo/TracedAi.java: PlayerControllerAi with every public overridable method wrapped to count 'delegated to Forge AI' calls.
Run after pulling a different Forge commit. Usage: gen_traced.py <PlayerControllerAi.java> <out TracedAi.java>"""
import re, sys
src = open(sys.argv[1]).read()
imports = "\n".join(l for l in src.splitlines() if l.startswith("import "))

def split_top(s):
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch in "<(": depth += 1
        if ch in ">)": depth -= 1
        if ch == "," and depth == 0: out.append(cur); cur = ""
        else: cur += ch
    if cur.strip(): out.append(cur)
    return out

methods, seen = [], set()
for m in re.finditer(r"^    public (?!static|final|class)(.*?)\)\s*\{", src, re.M | re.S):
    sig = " ".join(re.sub(r"/\*.*?\*/|//[^\n]*", "", m.group(1), flags=re.S).split()) + ")"
    i = sig.find("(")
    head, params = sig[:i], sig[i + 1:-1]
    toks = head.rsplit(" ", 1)
    if len(toks) != 2: continue
    rtype, name = toks
    if name in ("PlayerControllerAi",) or rtype == "": continue
    plist = [p.strip() for p in split_top(params)]
    plist = [re.sub(r"^final\s+", "", p) for p in plist if p]
    names = [p.rsplit(" ", 1)[1] for p in plist]
    key = (name, tuple(p.rsplit(" ", 1)[0] for p in plist))
    if key in seen: continue
    seen.add(key)
    methods.append((rtype, name, plist, names))

out = ["// GENERATED by tools/gen_traced.py. Do not edit.", "package silo;", imports, "import forge.game.Game;", "import forge.ai.PlayerControllerAi;", "import forge.ai.AiController;", "import forge.game.player.PlayerController.BinaryChoiceType;", "",
       "/** PlayerControllerAi with every public method counted as a delegation to Forge's AI. */",
       "public abstract class TracedAi extends PlayerControllerAi {", "    protected final Harness h;",
       "    protected TracedAi(Game g, Player p, LobbyPlayer lp, Harness h) { super(g, p, lp); this.h = h; }", ""]
for rtype, name, plist, names in methods:
    void = rtype.split()[-1] == "void"
    call = f"super.{name}({', '.join(names)})"
    out.append(f"    @Override public {rtype} {name}({', '.join(plist)}) {{ h.stats.delegated(\"{name}\"); {'' if void else 'return '}{call}; }}")
out.append("}")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print(len(methods), "methods wrapped")
