// GENERATED by tools/gen_traced.py. Do not edit.
package silo;
import com.google.common.collect.*;
import forge.LobbyPlayer;
import forge.StaticData;
import forge.ai.ability.ProtectAi;
import forge.card.CardStateName;
import forge.card.ColorSet;
import forge.card.ICardFace;
import forge.card.MagicColor;
import forge.card.mana.ManaCost;
import forge.card.mana.ManaCostShard;
import forge.deck.Deck;
import forge.deck.DeckSection;
import forge.game.*;
import forge.game.ability.AbilityUtils;
import forge.game.ability.ApiType;
import forge.game.ability.effects.CharmEffect;
import forge.game.ability.effects.RollDiceEffect;
import forge.game.card.*;
import forge.game.combat.Combat;
import forge.game.cost.*;
import forge.game.keyword.Keyword;
import forge.game.keyword.KeywordInterface;
import forge.game.mana.Mana;
import forge.game.mana.ManaConversionMatrix;
import forge.game.mana.ManaCostBeingPaid;
import forge.game.phase.PhaseHandler;
import forge.game.phase.PhaseType;
import forge.game.player.*;
import forge.game.replacement.ReplacementEffect;
import forge.game.spellability.*;
import forge.game.staticability.StaticAbility;
import forge.game.trigger.Trigger;
import forge.game.trigger.TriggerType;
import forge.game.trigger.WrappedAbility;
import forge.game.zone.PlayerZone;
import forge.game.zone.ZoneType;
import forge.item.PaperCard;
import forge.util.*;
import forge.util.collect.FCollection;
import forge.util.collect.FCollectionView;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.commons.lang3.tuple.Pair;
import java.util.*;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import forge.game.Game;
import forge.ai.PlayerControllerAi;
import forge.ai.AiController;
import forge.game.player.PlayerController.BinaryChoiceType;

/** PlayerControllerAi with every public method counted as a delegation to Forge's AI. */
public abstract class TracedAi extends PlayerControllerAi {
    protected final Harness h;
    protected TracedAi(Game g, Player p, LobbyPlayer lp, Harness h) { super(g, p, lp); this.h = h; }

    @Override public boolean pilotsNonAggroDeck() { h.stats.delegated("pilotsNonAggroDeck"); return super.pilotsNonAggroDeck(); }
    @Override public void setupAutoProfile(Deck deck) { h.stats.delegated("setupAutoProfile"); super.setupAutoProfile(deck); }
    @Override public SpellAbility getAbilityToPlay(Card hostCard, List<SpellAbility> abilities, ITriggerEvent triggerEvent) { h.stats.delegated("getAbilityToPlay"); return super.getAbilityToPlay(hostCard, abilities, triggerEvent); }
    @Override public AiController getAi() { h.stats.delegated("getAi"); return super.getAi(); }
    @Override public boolean isAI() { h.stats.delegated("isAI"); return super.isAI(); }
    @Override public List<PaperCard> sideboard(Deck deck, GameType gameType, String message) { h.stats.delegated("sideboard"); return super.sideboard(deck, gameType, message); }
    @Override public Map<Card, Integer> assignCombatDamage(Card attacker, CardCollectionView blockers, CardCollectionView remaining, int damageDealt, GameEntity defender, boolean overrideOrder) { h.stats.delegated("assignCombatDamage"); return super.assignCombatDamage(attacker, blockers, remaining, damageDealt, defender, overrideOrder); }
    @Override public Map<GameEntity, Integer> divideShield(Card effectSource, Map<GameEntity, Integer> affected, int shieldAmount) { h.stats.delegated("divideShield"); return super.divideShield(effectSource, affected, shieldAmount); }
    @Override public Map<Byte, Integer> specifyManaCombo(SpellAbility sa, ColorSet colorSet, int manaAmount, boolean different) { h.stats.delegated("specifyManaCombo"); return super.specifyManaCombo(sa, colorSet, manaAmount, different); }
    @Override public Integer announceRequirements(SpellAbility ability, int min, int max, String announce) { h.stats.delegated("announceRequirements"); return super.announceRequirements(ability, min, max, announce); }
    @Override public CardCollectionView choosePermanentsToSacrifice(SpellAbility sa, int min, int max, CardCollectionView validTargets, String message) { h.stats.delegated("choosePermanentsToSacrifice"); return super.choosePermanentsToSacrifice(sa, min, max, validTargets, message); }
    @Override public CardCollectionView choosePermanentsToDestroy(SpellAbility sa, int min, int max, CardCollectionView validTargets, String message) { h.stats.delegated("choosePermanentsToDestroy"); return super.choosePermanentsToDestroy(sa, min, max, validTargets, message); }
    @Override public CardCollectionView chooseCardsForEffect(CardCollectionView sourceList, SpellAbility sa, String title, int min, int max, boolean isOptional, Map<String, Object> params) { h.stats.delegated("chooseCardsForEffect"); return super.chooseCardsForEffect(sourceList, sa, title, min, max, isOptional, params); }
    @Override public List<Card> chooseContraptionsToCrank(List<Card> contraptions) { h.stats.delegated("chooseContraptionsToCrank"); return super.chooseContraptionsToCrank(contraptions); }
    @Override public boolean helpPayForAssistSpell(ManaCostBeingPaid cost, SpellAbility sa, int max, int requested) { h.stats.delegated("helpPayForAssistSpell"); return super.helpPayForAssistSpell(cost, sa, max, requested); }
    @Override public Player choosePlayerToAssistPayment(FCollectionView<Player> optionList, SpellAbility sa, String title, int max) { h.stats.delegated("choosePlayerToAssistPayment"); return super.choosePlayerToAssistPayment(optionList, sa, title, max); }
    @Override public <T extends GameEntity> T chooseSingleEntityForEffect(FCollectionView<T> optionList, DelayedReveal delayedReveal, SpellAbility sa, String title, boolean isOptional, Player targetedPlayer, Map<String, Object> params) { h.stats.delegated("chooseSingleEntityForEffect"); return super.chooseSingleEntityForEffect(optionList, delayedReveal, sa, title, isOptional, targetedPlayer, params); }
    @Override public <T extends GameEntity> List<T> chooseEntitiesForEffect(FCollectionView<T> optionList, int min, int max, DelayedReveal delayedReveal, SpellAbility sa, String title, Player targetedPlayer, Map<String, Object> params) { h.stats.delegated("chooseEntitiesForEffect"); return super.chooseEntitiesForEffect(optionList, min, max, delayedReveal, sa, title, targetedPlayer, params); }
    @Override public List<SpellAbility> chooseSpellAbilitiesForEffect(List<SpellAbility> spells, SpellAbility sa, String title, int num, Map<String, Object> params) { h.stats.delegated("chooseSpellAbilitiesForEffect"); return super.chooseSpellAbilitiesForEffect(spells, sa, title, num, params); }
    @Override public SpellAbility chooseSingleSpellForEffect(List<SpellAbility> spells, SpellAbility sa, String title, Map<String, Object> params) { h.stats.delegated("chooseSingleSpellForEffect"); return super.chooseSingleSpellForEffect(spells, sa, title, params); }
    @Override public boolean confirmAction(SpellAbility sa, PlayerActionConfirmMode mode, String message, List<String> options, Card cardToShow, Map<String, Object> params) { h.stats.delegated("confirmAction"); return super.confirmAction(sa, mode, message, options, cardToShow, params); }
    @Override public boolean confirmBidAction(SpellAbility sa, PlayerActionConfirmMode mode, String string, int bid, Player winner) { h.stats.delegated("confirmBidAction"); return super.confirmBidAction(sa, mode, string, bid, winner); }
    @Override public boolean confirmStaticApplication(Card hostCard, PlayerActionConfirmMode mode, String message, String logic) { h.stats.delegated("confirmStaticApplication"); return super.confirmStaticApplication(hostCard, mode, message, logic); }
    @Override public boolean acceptsDrawOffer() { h.stats.delegated("acceptsDrawOffer"); return super.acceptsDrawOffer(); }
    @Override public boolean confirmTrigger(WrappedAbility wrapper) { h.stats.delegated("confirmTrigger"); return super.confirmTrigger(wrapper); }
    @Override public boolean confirmPayment(CostPart costPart, String prompt, SpellAbility sa) { h.stats.delegated("confirmPayment"); return super.confirmPayment(costPart, prompt, sa); }
    @Override public boolean confirmReplacementEffect(ReplacementEffect replacementEffect, SpellAbility effectSA, GameEntity affected, String question) { h.stats.delegated("confirmReplacementEffect"); return super.confirmReplacementEffect(replacementEffect, effectSA, affected, question); }
    @Override public List<Card> exertAttackers(List<Card> attackers) { h.stats.delegated("exertAttackers"); return super.exertAttackers(attackers); }
    @Override public List<Card> enlistAttackers(List<Card> attackers) { h.stats.delegated("enlistAttackers"); return super.enlistAttackers(attackers); }
    @Override public CardCollection orderBlockers(Card attacker, CardCollection blockers) { h.stats.delegated("orderBlockers"); return super.orderBlockers(attacker, blockers); }
    @Override public CardCollection orderBlocker(Card attacker, Card blocker, CardCollection oldBlockers) { h.stats.delegated("orderBlocker"); return super.orderBlocker(attacker, blocker, oldBlockers); }
    @Override public CardCollection orderAttackers(Card blocker, CardCollection attackers) { h.stats.delegated("orderAttackers"); return super.orderAttackers(blocker, attackers); }
    @Override public void reveal(CardCollectionView cards, ZoneType zone, Player owner, String messagePrefix, boolean addSuffix) { h.stats.delegated("reveal"); super.reveal(cards, zone, owner, messagePrefix, addSuffix); }
    @Override public void reveal(List<CardView> cards, ZoneType zone, PlayerView owner, String messagePrefix, boolean addSuffix) { h.stats.delegated("reveal"); super.reveal(cards, zone, owner, messagePrefix, addSuffix); }
    @Override public ImmutablePair<CardCollection, CardCollection> arrangeForScry(CardCollection topN) { h.stats.delegated("arrangeForScry"); return super.arrangeForScry(topN); }
    @Override public ImmutablePair<CardCollection, CardCollection> arrangeForSurveil(CardCollection topN) { h.stats.delegated("arrangeForSurveil"); return super.arrangeForSurveil(topN); }
    @Override public boolean willPutCardOnTop(Card c) { h.stats.delegated("willPutCardOnTop"); return super.willPutCardOnTop(c); }
    @Override public CardCollectionView orderMoveToZoneList(CardCollectionView cards, ZoneType destinationZone, SpellAbility source) { h.stats.delegated("orderMoveToZoneList"); return super.orderMoveToZoneList(cards, destinationZone, source); }
    @Override public CardCollection chooseCardsToDiscardFrom(Player p, SpellAbility sa, CardCollection validCards, int min, int max, CardCollectionView visibleToChooser) { h.stats.delegated("chooseCardsToDiscardFrom"); return super.chooseCardsToDiscardFrom(p, sa, validCards, min, max, visibleToChooser); }
    @Override public void playSpellAbilityNoStack(SpellAbility effectSA, boolean canSetupTargets) { h.stats.delegated("playSpellAbilityNoStack"); super.playSpellAbilityNoStack(effectSA, canSetupTargets); }
    @Override public CardCollectionView chooseCardsToDelve(int genericAmount, CardCollection grave) { h.stats.delegated("chooseCardsToDelve"); return super.chooseCardsToDelve(genericAmount, grave); }
    @Override public CardCollectionView chooseCardsToDiscardUnlessType(int num, CardCollectionView hand, String[] uTypes, SpellAbility sa) { h.stats.delegated("chooseCardsToDiscardUnlessType"); return super.chooseCardsToDiscardUnlessType(num, hand, uTypes, sa); }
    @Override public Mana chooseManaFromPool(List<Mana> manaChoices) { h.stats.delegated("chooseManaFromPool"); return super.chooseManaFromPool(manaChoices); }
    @Override public String chooseSomeType(String kindOfType, SpellAbility sa, Collection<String> validTypes, boolean isOptional) { h.stats.delegated("chooseSomeType"); return super.chooseSomeType(kindOfType, sa, validTypes, isOptional); }
    @Override public Object vote(SpellAbility sa, String prompt, List<Object> options, ListMultimap<Object, Player> votes, Player forPlayer, boolean optional) { h.stats.delegated("vote"); return super.vote(sa, prompt, options, votes, forPlayer, optional); }
    @Override public String chooseSector(Card assignee, String ai, List<String> sectors) { h.stats.delegated("chooseSector"); return super.chooseSector(assignee, ai, sectors); }
    @Override public int chooseSprocket(Card assignee, List<Integer> sprockets) { h.stats.delegated("chooseSprocket"); return super.chooseSprocket(assignee, sprockets); }
    @Override public PlanarDice choosePDRollToIgnore(List<PlanarDice> rolls) { h.stats.delegated("choosePDRollToIgnore"); return super.choosePDRollToIgnore(rolls); }
    @Override public Integer chooseRollToIgnore(List<Integer> rolls) { h.stats.delegated("chooseRollToIgnore"); return super.chooseRollToIgnore(rolls); }
    @Override public List<Integer> chooseDiceToReroll(List<Integer> rolls) { h.stats.delegated("chooseDiceToReroll"); return super.chooseDiceToReroll(rolls); }
    @Override public Integer chooseRollToModify(List<Integer> rolls) { h.stats.delegated("chooseRollToModify"); return super.chooseRollToModify(rolls); }
    @Override public RollDiceEffect.DieRollResult chooseRollToSwap(List<RollDiceEffect.DieRollResult> rolls) { h.stats.delegated("chooseRollToSwap"); return super.chooseRollToSwap(rolls); }
    @Override public String chooseRollSwapValue(List<String> swapChoices, Integer currentResult, int power, int toughness) { h.stats.delegated("chooseRollSwapValue"); return super.chooseRollSwapValue(swapChoices, currentResult, power, toughness); }
    @Override public boolean mulliganKeepHand(Player firstPlayer, int cardsToReturn) { h.stats.delegated("mulliganKeepHand"); return super.mulliganKeepHand(firstPlayer, cardsToReturn); }
    @Override public CardCollectionView tuckCardsViaMulligan(CardCollectionView hand, int cardsToReturn) { h.stats.delegated("tuckCardsViaMulligan"); return super.tuckCardsViaMulligan(hand, cardsToReturn); }
    @Override public void declareAttackers(Player attacker, Combat combat) { h.stats.delegated("declareAttackers"); super.declareAttackers(attacker, combat); }
    @Override public void declareBlockers(Player defender, Combat combat) { h.stats.delegated("declareBlockers"); super.declareBlockers(defender, combat); }
    @Override public List<SpellAbility> chooseSpellAbilityToPlay() { h.stats.delegated("chooseSpellAbilityToPlay"); return super.chooseSpellAbilityToPlay(); }
    @Override public boolean playChosenSpellAbility(SpellAbility sa) { h.stats.delegated("playChosenSpellAbility"); return super.playChosenSpellAbility(sa); }
    @Override public CardCollectionView chooseCardsToDiscardToMaximumHandSize(int numDiscard) { h.stats.delegated("chooseCardsToDiscardToMaximumHandSize"); return super.chooseCardsToDiscardToMaximumHandSize(numDiscard); }
    @Override public CardCollectionView chooseCardsToRevealFromHand(int min, int max, CardCollectionView valid) { h.stats.delegated("chooseCardsToRevealFromHand"); return super.chooseCardsToRevealFromHand(min, max, valid); }
    @Override public Player chooseStartingPlayer(boolean isFirstGame) { h.stats.delegated("chooseStartingPlayer"); return super.chooseStartingPlayer(isFirstGame); }
    @Override public PlayerZone chooseStartingHand(List<PlayerZone> zones) { h.stats.delegated("chooseStartingHand"); return super.chooseStartingHand(zones); }
    @Override public List<SpellAbility> chooseSaToActivateFromOpeningHand(List<SpellAbility> usableFromOpeningHand) { h.stats.delegated("chooseSaToActivateFromOpeningHand"); return super.chooseSaToActivateFromOpeningHand(usableFromOpeningHand); }
    @Override public int chooseNumber(SpellAbility sa, String title, int min, int max) { h.stats.delegated("chooseNumber"); return super.chooseNumber(sa, title, min, max); }
    @Override public int chooseNumber(SpellAbility sa, String string, int min, int max, Map<String, Object> params) { h.stats.delegated("chooseNumber"); return super.chooseNumber(sa, string, min, max, params); }
    @Override public int chooseNumber(SpellAbility sa, String title, List<Integer> options, Player relatedPlayer) { h.stats.delegated("chooseNumber"); return super.chooseNumber(sa, title, options, relatedPlayer); }
    @Override public boolean chooseFlipResult(SpellAbility sa, Player flipper, boolean call) { h.stats.delegated("chooseFlipResult"); return super.chooseFlipResult(sa, flipper, call); }
    @Override public Pair<SpellAbilityStackInstance, GameObject> chooseTarget(SpellAbility saSrc, List<Pair<SpellAbilityStackInstance, GameObject>> allTargets) { h.stats.delegated("chooseTarget"); return super.chooseTarget(saSrc, allTargets); }
    @Override public void notifyOfValue(SpellAbility saSource, GameObject realtedTarget, String value) { h.stats.delegated("notifyOfValue"); super.notifyOfValue(saSource, realtedTarget, value); }
    @Override public boolean chooseBinary(SpellAbility sa, String question, BinaryChoiceType kindOfChoice, Boolean defaultVal) { h.stats.delegated("chooseBinary"); return super.chooseBinary(sa, question, kindOfChoice, defaultVal); }
    @Override public boolean chooseBinary(SpellAbility sa, String question, BinaryChoiceType kindOfChoice, Map<String, Object> params) { h.stats.delegated("chooseBinary"); return super.chooseBinary(sa, question, kindOfChoice, params); }
    @Override public List<AbilitySub> chooseModeForAbility(SpellAbility sa, List<AbilitySub> possible, int min, int num, boolean allowRepeat) { h.stats.delegated("chooseModeForAbility"); return super.chooseModeForAbility(sa, possible, min, num, allowRepeat); }
    @Override public byte chooseColorAllowColorless(String message, Card card, ColorSet colors) { h.stats.delegated("chooseColorAllowColorless"); return super.chooseColorAllowColorless(message, card, colors); }
    @Override public byte chooseColor(String message, SpellAbility sa, ColorSet colors) { h.stats.delegated("chooseColor"); return super.chooseColor(message, sa, colors); }
    @Override public ColorSet chooseColors(String message, SpellAbility sa, int min, int max, ColorSet options) { h.stats.delegated("chooseColors"); return super.chooseColors(message, sa, min, max, options); }
    @Override public CounterType chooseCounterType(List<CounterType> options, SpellAbility sa, String prompt, Map<String, Object> params) { h.stats.delegated("chooseCounterType"); return super.chooseCounterType(options, sa, prompt, params); }
    @Override public String chooseKeywordForPump(List<String> options, SpellAbility sa, String prompt, Card tgtCard) { h.stats.delegated("chooseKeywordForPump"); return super.chooseKeywordForPump(options, sa, prompt, tgtCard); }
    @Override public ReplacementEffect chooseSingleReplacementEffect(List<ReplacementEffect> possibleReplacers) { h.stats.delegated("chooseSingleReplacementEffect"); return super.chooseSingleReplacementEffect(possibleReplacers); }
    @Override public StaticAbility chooseSingleStaticAbility(List<StaticAbility> possibleStatics) { h.stats.delegated("chooseSingleStaticAbility"); return super.chooseSingleStaticAbility(possibleStatics); }
    @Override public String chooseProtectionType(SpellAbility sa, List<String> choices) { h.stats.delegated("chooseProtectionType"); return super.chooseProtectionType(sa, choices); }
    @Override public boolean payManaCost(ManaCost toPay, CostPartMana costPartMana, SpellAbility sa, String prompt, ManaConversionMatrix matrix, boolean effect) { h.stats.delegated("payManaCost"); return super.payManaCost(toPay, costPartMana, sa, prompt, matrix, effect); }
    @Override public boolean payCombatCost(Card c, Cost cost, SpellAbility sa, String prompt) { h.stats.delegated("payCombatCost"); return super.payCombatCost(c, cost, sa, prompt); }
    @Override public CardCollectionView chooseCardsForCost(CardCollectionView optionList, SpellAbility sa, CostPartWithList cpl, int amount, boolean isOptional, String prompt) { h.stats.delegated("chooseCardsForCost"); return super.chooseCardsForCost(optionList, sa, cpl, amount, isOptional, prompt); }
    @Override public boolean applyManaToCost(ManaCostBeingPaid toPay, SpellAbility ability, String prompt, ManaConversionMatrix matrix, boolean effect) { h.stats.delegated("applyManaToCost"); return super.applyManaToCost(toPay, ability, prompt, matrix, effect); }
    @Override public CostDecisionMakerBase getCostDecisionMaker(Player player, SpellAbility ability, boolean effect, String prompt) { h.stats.delegated("getCostDecisionMaker"); return super.getCostDecisionMaker(player, ability, effect, prompt); }
    @Override public boolean payCostToPreventEffect(Cost cost, SpellAbility sa, boolean alreadyPaid, FCollectionView<Player> allPayers) { h.stats.delegated("payCostToPreventEffect"); return super.payCostToPreventEffect(cost, sa, alreadyPaid, allPayers); }
    @Override public boolean payCostDuringRoll(Cost cost, SpellAbility sa) { h.stats.delegated("payCostDuringRoll"); return super.payCostDuringRoll(cost, sa); }
    @Override public List<SpellAbility> orderSimultaneousSa(List<SpellAbility> activePlayerSAs) { h.stats.delegated("orderSimultaneousSa"); return super.orderSimultaneousSa(activePlayerSAs); }
    @Override public void orderAndPlaySimultaneousSa(List<SpellAbility> activePlayerSAs) { h.stats.delegated("orderAndPlaySimultaneousSa"); super.orderAndPlaySimultaneousSa(activePlayerSAs); }
    @Override public boolean playTrigger(Card host, WrappedAbility wrapperAbility, boolean isMandatory) { h.stats.delegated("playTrigger"); return super.playTrigger(host, wrapperAbility, isMandatory); }
    @Override public boolean playSaFromPlayEffect(SpellAbility tgtSA) { h.stats.delegated("playSaFromPlayEffect"); return super.playSaFromPlayEffect(tgtSA); }
    @Override public boolean chooseTargetsFor(SpellAbility currentAbility) { h.stats.delegated("chooseTargetsFor"); return super.chooseTargetsFor(currentAbility); }
    @Override public TargetChoices chooseNewTargetsFor(SpellAbility ability, Predicate<GameObject> filter, boolean optional) { h.stats.delegated("chooseNewTargetsFor"); return super.chooseNewTargetsFor(ability, filter, optional); }
    @Override public boolean chooseCardsPile(SpellAbility sa, CardCollectionView pile1, CardCollectionView pile2, String faceUp) { h.stats.delegated("chooseCardsPile"); return super.chooseCardsPile(sa, pile1, pile2, faceUp); }
    @Override public void revealAnte(String message, Multimap<Player, PaperCard> removedAnteCards) { h.stats.delegated("revealAnte"); super.revealAnte(message, removedAnteCards); }
    @Override public void revealAISkipCards(String message, Map<Player, Map<DeckSection, List<? extends PaperCard>>> deckCards) { h.stats.delegated("revealAISkipCards"); super.revealAISkipCards(message, deckCards); }
    @Override public void revealUnsupported(Map<Player, List<PaperCard>> unsupported) { h.stats.delegated("revealUnsupported"); super.revealUnsupported(unsupported); }
    @Override public Map<DeckSection, List<? extends PaperCard>> complainCardsCantPlayWell(Deck myDeck) { h.stats.delegated("complainCardsCantPlayWell"); return super.complainCardsCantPlayWell(myDeck); }
    @Override public CardCollectionView cheatShuffle(CardCollectionView list) { h.stats.delegated("cheatShuffle"); return super.cheatShuffle(list); }
    @Override public List<PaperCard> chooseCardsYouWonToAddToDeck(List<PaperCard> losses) { h.stats.delegated("chooseCardsYouWonToAddToDeck"); return super.chooseCardsYouWonToAddToDeck(losses); }
    @Override public Map<Card, ManaCostShard> chooseCardsForConvokeOrImprovise(SpellAbility sa, ManaCost manaCost, CardCollectionView untappedCards, boolean artifacts, boolean creatures, Integer maxReduction) { h.stats.delegated("chooseCardsForConvokeOrImprovise"); return super.chooseCardsForConvokeOrImprovise(sa, manaCost, untappedCards, artifacts, creatures, maxReduction); }
    @Override public String chooseCardName(SpellAbility sa, List<ICardFace> faces, String message) { h.stats.delegated("chooseCardName"); return super.chooseCardName(sa, faces, message); }
    @Override public String chooseCardName(SpellAbility sa, Predicate<ICardFace> cpp, String valid, String message) { h.stats.delegated("chooseCardName"); return super.chooseCardName(sa, cpp, valid, message); }
    @Override public Card chooseSingleCardForZoneChange(ZoneType destination, List<ZoneType> origin, SpellAbility sa, CardCollection fetchList, DelayedReveal delayedReveal, String selectPrompt, boolean isOptional, Player decider) { h.stats.delegated("chooseSingleCardForZoneChange"); return super.chooseSingleCardForZoneChange(destination, origin, sa, fetchList, delayedReveal, selectPrompt, isOptional, decider); }
    @Override public List<Card> chooseCardsForZoneChange(ZoneType destination, List<ZoneType> origin, SpellAbility sa, CardCollection fetchList, int min, int max, DelayedReveal delayedReveal, String selectPrompt, Player decider) { h.stats.delegated("chooseCardsForZoneChange"); return super.chooseCardsForZoneChange(destination, origin, sa, fetchList, min, max, delayedReveal, selectPrompt, decider); }
    @Override public void resetAtEndOfTurn() { h.stats.delegated("resetAtEndOfTurn"); super.resetAtEndOfTurn(); }
    @Override public void autoPassCancel() { h.stats.delegated("autoPassCancel"); super.autoPassCancel(); }
    @Override public void awaitNextInput() { h.stats.delegated("awaitNextInput"); super.awaitNextInput(); }
    @Override public void cancelAwaitNextInput() { h.stats.delegated("cancelAwaitNextInput"); super.cancelAwaitNextInput(); }
    @Override public ICardFace chooseSingleCardFace(SpellAbility sa, List<ICardFace> faces, String message) { h.stats.delegated("chooseSingleCardFace"); return super.chooseSingleCardFace(sa, faces, message); }
    @Override public ICardFace chooseSingleCardFace(SpellAbility sa, String message, Predicate<ICardFace> cpp, String name) { h.stats.delegated("chooseSingleCardFace"); return super.chooseSingleCardFace(sa, message, cpp, name); }
    @Override public CardState chooseSingleCardState(SpellAbility sa, List<CardState> states, String message, Map<String, Object> params) { h.stats.delegated("chooseSingleCardState"); return super.chooseSingleCardState(sa, states, message, params); }
    @Override public List<Card> chooseCardsForSplice(SpellAbility sa, List<Card> cards) { h.stats.delegated("chooseCardsForSplice"); return super.chooseCardsForSplice(sa, cards); }
    @Override public List<OptionalCostValue> chooseOptionalCosts(SpellAbility chosen, List<OptionalCostValue> optionalCostValues) { h.stats.delegated("chooseOptionalCosts"); return super.chooseOptionalCosts(chosen, optionalCostValues); }
    @Override public int chooseNumberForKeywordCost(SpellAbility sa, Cost cost, KeywordInterface keyword, String prompt, int max) { h.stats.delegated("chooseNumberForKeywordCost"); return super.chooseNumberForKeywordCost(sa, cost, keyword, prompt, max); }
    @Override public int chooseNumberForCostReduction(SpellAbility sa, int min, int max) { h.stats.delegated("chooseNumberForCostReduction"); return super.chooseNumberForCostReduction(sa, min, max); }
    @Override public List<CostPart> orderCosts(List<CostPart> costs) { h.stats.delegated("orderCosts"); return super.orderCosts(costs); }
    @Override public CardCollection chooseCardsForEffectMultiple(Map<String, CardCollection> validMap, SpellAbility sa, String title, boolean isOptional) { h.stats.delegated("chooseCardsForEffectMultiple"); return super.chooseCardsForEffectMultiple(validMap, sa, title, isOptional); }
}
