#!/usr/bin/env python3
"""Generate itest/LogAi.java: PlayerControllerAi with every public overridable method wrapped to log (method, args, result) into Probe.LOG.
Adapted from the Phase 1 serializer tools/gen_traced.py.
Run after pulling a different Forge commit. Usage: gen_traced.py <PlayerControllerAi.java> <out TracedAi.java>"""
import re, sys
src = open(sys.argv[1]).read()
imports = "\n".join(l for l in src.splitlines() if l.startswith("import "))

def split_top(s):
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch in "<(": depth += 1
        if ch in ">)": depth -= 1
        if ch == "," and depth == 0: out.append(cur); cur = ""
        else: cur += ch
    if cur.strip(): out.append(cur)
    return out

methods, seen = [], set()
for m in re.finditer(r"^    public (?!static|final|class)(.*?)\)\s*\{", src, re.M | re.S):
    sig = " ".join(re.sub(r"/\*.*?\*/|//[^\n]*", "", m.group(1), flags=re.S).split()) + ")"
    i = sig.find("(")
    head, params = sig[:i], sig[i + 1:-1]
    toks = head.rsplit(" ", 1)
    if len(toks) != 2: continue
    rtype, name = toks
    if name in ("PlayerControllerAi",) or rtype == "": continue
    plist = [p.strip() for p in split_top(params)]
    plist = [re.sub(r"^final\s+", "", p) for p in plist if p]
    names = [p.rsplit(" ", 1)[1] for p in plist]
    key = (name, tuple(p.rsplit(" ", 1)[0] for p in plist))
    if key in seen: continue
    seen.add(key)
    methods.append((rtype, name, plist, names))

out = ["// GENERATED by tools/gen_logai.py. Do not edit.", "package itest;", imports, "import forge.game.Game;", "import forge.ai.PlayerControllerAi;", "import forge.ai.AiController;", "import forge.game.player.PlayerController.BinaryChoiceType;", "",
       "/** PlayerControllerAi that logs every public decision call (method, arguments, result) for the lockstep follower. */",
       "public abstract class LogAi extends PlayerControllerAi {",
       "    protected LogAi(Game g, Player p, LobbyPlayer lp) { super(g, p, lp); }", ""]
SKIP = {"chooseSpellAbilityToPlay", "playChosenSpellAbility", "getAi", "getGame", "getPlayer", "getLobbyPlayer"}
for rtype, name, plist, names in methods:
    if name in SKIP or name.startswith("get") or name.startswith("is") or name.startswith("set") or name.startswith("can"):
        out.append(f"    @Override public {rtype} {name}({', '.join(plist)}) {{ {'' if rtype.split()[-1]=='void' else 'return '}super.{name}({', '.join(names)}); }}")
        continue
    void = rtype.split()[-1] == "void"
    args = ", ".join(names)
    if void:
        out.append(f"    @Override public {rtype} {name}({', '.join(plist)}) {{ super.{name}({args}); Probe.log(player, \"{name}\", new Object[]{{{args}}}, null); }}")
    else:
        out.append(f"    @Override public {rtype} {name}({', '.join(plist)}) {{ var r__ = super.{name}({args}); Probe.log(player, \"{name}\", new Object[]{{{args}}}, r__); return r__; }}")
out.append("}")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print(len(methods), "methods wrapped")
