// GENERATED by tools/gen_logai.py. Do not edit.
package itest;
import com.google.common.collect.*;
import forge.LobbyPlayer;
import forge.StaticData;
import forge.ai.ability.ProtectAi;
import forge.card.CardStateName;
import forge.card.ColorSet;
import forge.card.ICardFace;
import forge.card.MagicColor;
import forge.card.mana.ManaCost;
import forge.card.mana.ManaCostShard;
import forge.deck.Deck;
import forge.deck.DeckSection;
import forge.game.*;
import forge.game.ability.AbilityUtils;
import forge.game.ability.ApiType;
import forge.game.ability.effects.CharmEffect;
import forge.game.ability.effects.RollDiceEffect;
import forge.game.card.*;
import forge.game.combat.Combat;
import forge.game.cost.*;
import forge.game.keyword.Keyword;
import forge.game.keyword.KeywordInterface;
import forge.game.mana.Mana;
import forge.game.mana.ManaConversionMatrix;
import forge.game.mana.ManaCostBeingPaid;
import forge.game.phase.PhaseHandler;
import forge.game.phase.PhaseType;
import forge.game.player.*;
import forge.game.replacement.ReplacementEffect;
import forge.game.spellability.*;
import forge.game.staticability.StaticAbility;
import forge.game.trigger.Trigger;
import forge.game.trigger.TriggerType;
import forge.game.trigger.WrappedAbility;
import forge.game.zone.PlayerZone;
import forge.game.zone.ZoneType;
import forge.item.PaperCard;
import forge.util.*;
import forge.util.collect.FCollection;
import forge.util.collect.FCollectionView;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.commons.lang3.tuple.Pair;
import java.util.*;
import java.util.function.Consumer;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import forge.game.Game;
import forge.ai.PlayerControllerAi;
import forge.ai.AiController;
import forge.game.player.PlayerController.BinaryChoiceType;

/** PlayerControllerAi that logs every public decision call (method, arguments, result) for the lockstep follower. */
public abstract class LogAi extends PlayerControllerAi {
    protected LogAi(Game g, Player p, LobbyPlayer lp) { super(g, p, lp); }

    @Override public boolean pilotsNonAggroDeck() { var r__ = super.pilotsNonAggroDeck(); Probe.log(player, "pilotsNonAggroDeck", new Object[]{}, r__); return r__; }
    @Override public void setupAutoProfile(Deck deck) { super.setupAutoProfile(deck); }
    @Override public SpellAbility getAbilityToPlay(Card hostCard, List<SpellAbility> abilities, ITriggerEvent triggerEvent) { return super.getAbilityToPlay(hostCard, abilities, triggerEvent); }
    @Override public AiController getAi() { return super.getAi(); }
    @Override public boolean isAI() { return super.isAI(); }
    @Override public List<PaperCard> sideboard(Deck deck, GameType gameType, String message) { var r__ = super.sideboard(deck, gameType, message); Probe.log(player, "sideboard", new Object[]{deck, gameType, message}, r__); return r__; }
    @Override public Map<Card, Integer> assignCombatDamage(Card attacker, CardCollectionView blockers, CardCollectionView remaining, int damageDealt, GameEntity defender, boolean overrideOrder) { var r__ = super.assignCombatDamage(attacker, blockers, remaining, damageDealt, defender, overrideOrder); Probe.log(player, "assignCombatDamage", new Object[]{attacker, blockers, remaining, damageDealt, defender, overrideOrder}, r__); return r__; }
    @Override public Map<GameEntity, Integer> divideShield(Card effectSource, Map<GameEntity, Integer> affected, int shieldAmount) { var r__ = super.divideShield(effectSource, affected, shieldAmount); Probe.log(player, "divideShield", new Object[]{effectSource, affected, shieldAmount}, r__); return r__; }
    @Override public Map<Byte, Integer> specifyManaCombo(SpellAbility sa, ColorSet colorSet, int manaAmount, boolean different) { var r__ = super.specifyManaCombo(sa, colorSet, manaAmount, different); Probe.log(player, "specifyManaCombo", new Object[]{sa, colorSet, manaAmount, different}, r__); return r__; }
    @Override public Integer announceRequirements(SpellAbility ability, int min, int max, String announce) { var r__ = super.announceRequirements(ability, min, max, announce); Probe.log(player, "announceRequirements", new Object[]{ability, min, max, announce}, r__); return r__; }
    @Override public CardCollectionView choosePermanentsToSacrifice(SpellAbility sa, int min, int max, CardCollectionView validTargets, String message) { var r__ = super.choosePermanentsToSacrifice(sa, min, max, validTargets, message); Probe.log(player, "choosePermanentsToSacrifice", new Object[]{sa, min, max, validTargets, message}, r__); return r__; }
    @Override public CardCollectionView choosePermanentsToDestroy(SpellAbility sa, int min, int max, CardCollectionView validTargets, String message) { var r__ = super.choosePermanentsToDestroy(sa, min, max, validTargets, message); Probe.log(player, "choosePermanentsToDestroy", new Object[]{sa, min, max, validTargets, message}, r__); return r__; }
    @Override public CardCollectionView chooseCardsForEffect(CardCollectionView sourceList, SpellAbility sa, String title, int min, int max, boolean isOptional, Map<String, Object> params) { var r__ = super.chooseCardsForEffect(sourceList, sa, title, min, max, isOptional, params); Probe.log(player, "chooseCardsForEffect", new Object[]{sourceList, sa, title, min, max, isOptional, params}, r__); return r__; }
    @Override public List<Card> chooseContraptionsToCrank(List<Card> contraptions) { var r__ = super.chooseContraptionsToCrank(contraptions); Probe.log(player, "chooseContraptionsToCrank", new Object[]{contraptions}, r__); return r__; }
    @Override public boolean helpPayForAssistSpell(ManaCostBeingPaid cost, SpellAbility sa, int max, int requested) { var r__ = super.helpPayForAssistSpell(cost, sa, max, requested); Probe.log(player, "helpPayForAssistSpell", new Object[]{cost, sa, max, requested}, r__); return r__; }
    @Override public Player choosePlayerToAssistPayment(FCollectionView<Player> optionList, SpellAbility sa, String title, int max) { var r__ = super.choosePlayerToAssistPayment(optionList, sa, title, max); Probe.log(player, "choosePlayerToAssistPayment", new Object[]{optionList, sa, title, max}, r__); return r__; }
    @Override public <T extends GameEntity> T chooseSingleEntityForEffect(FCollectionView<T> optionList, DelayedReveal delayedReveal, SpellAbility sa, String title, boolean isOptional, Player targetedPlayer, Map<String, Object> params) { var r__ = super.chooseSingleEntityForEffect(optionList, delayedReveal, sa, title, isOptional, targetedPlayer, params); Probe.log(player, "chooseSingleEntityForEffect", new Object[]{optionList, delayedReveal, sa, title, isOptional, targetedPlayer, params}, r__); return r__; }
    @Override public <T extends GameEntity> List<T> chooseEntitiesForEffect(FCollectionView<T> optionList, int min, int max, DelayedReveal delayedReveal, SpellAbility sa, String title, Player targetedPlayer, Map<String, Object> params) { var r__ = super.chooseEntitiesForEffect(optionList, min, max, delayedReveal, sa, title, targetedPlayer, params); Probe.log(player, "chooseEntitiesForEffect", new Object[]{optionList, min, max, delayedReveal, sa, title, targetedPlayer, params}, r__); return r__; }
    @Override public List<SpellAbility> chooseSpellAbilitiesForEffect(List<SpellAbility> spells, SpellAbility sa, String title, int num, Map<String, Object> params) { var r__ = super.chooseSpellAbilitiesForEffect(spells, sa, title, num, params); Probe.log(player, "chooseSpellAbilitiesForEffect", new Object[]{spells, sa, title, num, params}, r__); return r__; }
    @Override public SpellAbility chooseSingleSpellForEffect(List<SpellAbility> spells, SpellAbility sa, String title, Map<String, Object> params) { var r__ = super.chooseSingleSpellForEffect(spells, sa, title, params); Probe.log(player, "chooseSingleSpellForEffect", new Object[]{spells, sa, title, params}, r__); return r__; }
    @Override public boolean confirmAction(SpellAbility sa, PlayerActionConfirmMode mode, String message, List<String> options, Card cardToShow, Map<String, Object> params) { var r__ = super.confirmAction(sa, mode, message, options, cardToShow, params); Probe.log(player, "confirmAction", new Object[]{sa, mode, message, options, cardToShow, params}, r__); return r__; }
    @Override public boolean confirmBidAction(SpellAbility sa, PlayerActionConfirmMode mode, String string, int bid, Player winner) { var r__ = super.confirmBidAction(sa, mode, string, bid, winner); Probe.log(player, "confirmBidAction", new Object[]{sa, mode, string, bid, winner}, r__); return r__; }
    @Override public boolean confirmStaticApplication(Card hostCard, PlayerActionConfirmMode mode, String message, String logic) { var r__ = super.confirmStaticApplication(hostCard, mode, message, logic); Probe.log(player, "confirmStaticApplication", new Object[]{hostCard, mode, message, logic}, r__); return r__; }
    @Override public boolean acceptsDrawOffer() { var r__ = super.acceptsDrawOffer(); Probe.log(player, "acceptsDrawOffer", new Object[]{}, r__); return r__; }
    @Override public boolean confirmTrigger(WrappedAbility wrapper) { var r__ = super.confirmTrigger(wrapper); Probe.log(player, "confirmTrigger", new Object[]{wrapper}, r__); return r__; }
    @Override public boolean confirmPayment(CostPart costPart, String prompt, SpellAbility sa) { var r__ = super.confirmPayment(costPart, prompt, sa); Probe.log(player, "confirmPayment", new Object[]{costPart, prompt, sa}, r__); return r__; }
    @Override public boolean confirmReplacementEffect(ReplacementEffect replacementEffect, SpellAbility effectSA, GameEntity affected, String question) { var r__ = super.confirmReplacementEffect(replacementEffect, effectSA, affected, question); Probe.log(player, "confirmReplacementEffect", new Object[]{replacementEffect, effectSA, affected, question}, r__); return r__; }
    @Override public List<Card> exertAttackers(List<Card> attackers) { var r__ = super.exertAttackers(attackers); Probe.log(player, "exertAttackers", new Object[]{attackers}, r__); return r__; }
    @Override public List<Card> enlistAttackers(List<Card> attackers) { var r__ = super.enlistAttackers(attackers); Probe.log(player, "enlistAttackers", new Object[]{attackers}, r__); return r__; }
    @Override public CardCollection orderBlockers(Card attacker, CardCollection blockers) { var r__ = super.orderBlockers(attacker, blockers); Probe.log(player, "orderBlockers", new Object[]{attacker, blockers}, r__); return r__; }
    @Override public CardCollection orderBlocker(Card attacker, Card blocker, CardCollection oldBlockers) { var r__ = super.orderBlocker(attacker, blocker, oldBlockers); Probe.log(player, "orderBlocker", new Object[]{attacker, blocker, oldBlockers}, r__); return r__; }
    @Override public CardCollection orderAttackers(Card blocker, CardCollection attackers) { var r__ = super.orderAttackers(blocker, attackers); Probe.log(player, "orderAttackers", new Object[]{blocker, attackers}, r__); return r__; }
    @Override public void reveal(CardCollectionView cards, ZoneType zone, Player owner, String messagePrefix, boolean addSuffix) { super.reveal(cards, zone, owner, messagePrefix, addSuffix); Probe.log(player, "reveal", new Object[]{cards, zone, owner, messagePrefix, addSuffix}, null); }
    @Override public void reveal(List<CardView> cards, ZoneType zone, PlayerView owner, String messagePrefix, boolean addSuffix) { super.reveal(cards, zone, owner, messagePrefix, addSuffix); Probe.log(player, "reveal", new Object[]{cards, zone, owner, messagePrefix, addSuffix}, null); }
    @Override public ImmutablePair<CardCollection, CardCollection> arrangeForScry(CardCollection topN) { var r__ = super.arrangeForScry(topN); Probe.log(player, "arrangeForScry", new Object[]{topN}, r__); return r__; }
    @Override public ImmutablePair<CardCollection, CardCollection> arrangeForSurveil(CardCollection topN) { var r__ = super.arrangeForSurveil(topN); Probe.log(player, "arrangeForSurveil", new Object[]{topN}, r__); return r__; }
    @Override public boolean willPutCardOnTop(Card c) { var r__ = super.willPutCardOnTop(c); Probe.log(player, "willPutCardOnTop", new Object[]{c}, r__); return r__; }
    @Override public CardCollectionView orderMoveToZoneList(CardCollectionView cards, ZoneType destinationZone, SpellAbility source) { var r__ = super.orderMoveToZoneList(cards, destinationZone, source); Probe.log(player, "orderMoveToZoneList", new Object[]{cards, destinationZone, source}, r__); return r__; }
    @Override public CardCollection chooseCardsToDiscardFrom(Player p, SpellAbility sa, CardCollection validCards, int min, int max, CardCollectionView visibleToChooser) { var r__ = super.chooseCardsToDiscardFrom(p, sa, validCards, min, max, visibleToChooser); Probe.log(player, "chooseCardsToDiscardFrom", new Object[]{p, sa, validCards, min, max, visibleToChooser}, r__); return r__; }
    @Override public void playSpellAbilityNoStack(SpellAbility effectSA, boolean canSetupTargets) { super.playSpellAbilityNoStack(effectSA, canSetupTargets); Probe.log(player, "playSpellAbilityNoStack", new Object[]{effectSA, canSetupTargets}, null); }
    @Override public CardCollectionView chooseCardsToDelve(int genericAmount, CardCollection grave) { var r__ = super.chooseCardsToDelve(genericAmount, grave); Probe.log(player, "chooseCardsToDelve", new Object[]{genericAmount, grave}, r__); return r__; }
    @Override public CardCollectionView chooseCardsToDiscardUnlessType(int num, CardCollectionView hand, String[] uTypes, SpellAbility sa) { var r__ = super.chooseCardsToDiscardUnlessType(num, hand, uTypes, sa); Probe.log(player, "chooseCardsToDiscardUnlessType", new Object[]{num, hand, uTypes, sa}, r__); return r__; }
    @Override public Mana chooseManaFromPool(List<Mana> manaChoices) { var r__ = super.chooseManaFromPool(manaChoices); Probe.log(player, "chooseManaFromPool", new Object[]{manaChoices}, r__); return r__; }
    @Override public String chooseSomeType(String kindOfType, SpellAbility sa, Collection<String> validTypes, boolean isOptional) { var r__ = super.chooseSomeType(kindOfType, sa, validTypes, isOptional); Probe.log(player, "chooseSomeType", new Object[]{kindOfType, sa, validTypes, isOptional}, r__); return r__; }
    @Override public Object vote(SpellAbility sa, String prompt, List<Object> options, ListMultimap<Object, Player> votes, Player forPlayer, boolean optional) { var r__ = super.vote(sa, prompt, options, votes, forPlayer, optional); Probe.log(player, "vote", new Object[]{sa, prompt, options, votes, forPlayer, optional}, r__); return r__; }
    @Override public String chooseSector(Card assignee, String ai, List<String> sectors) { var r__ = super.chooseSector(assignee, ai, sectors); Probe.log(player, "chooseSector", new Object[]{assignee, ai, sectors}, r__); return r__; }
    @Override public int chooseSprocket(Card assignee, List<Integer> sprockets) { var r__ = super.chooseSprocket(assignee, sprockets); Probe.log(player, "chooseSprocket", new Object[]{assignee, sprockets}, r__); return r__; }
    @Override public PlanarDice choosePDRollToIgnore(List<PlanarDice> rolls) { var r__ = super.choosePDRollToIgnore(rolls); Probe.log(player, "choosePDRollToIgnore", new Object[]{rolls}, r__); return r__; }
    @Override public Integer chooseRollToIgnore(List<Integer> rolls) { var r__ = super.chooseRollToIgnore(rolls); Probe.log(player, "chooseRollToIgnore", new Object[]{rolls}, r__); return r__; }
    @Override public List<Integer> chooseDiceToReroll(List<Integer> rolls) { var r__ = super.chooseDiceToReroll(rolls); Probe.log(player, "chooseDiceToReroll", new Object[]{rolls}, r__); return r__; }
    @Override public Integer chooseRollToModify(List<Integer> rolls) { var r__ = super.chooseRollToModify(rolls); Probe.log(player, "chooseRollToModify", new Object[]{rolls}, r__); return r__; }
    @Override public RollDiceEffect.DieRollResult chooseRollToSwap(List<RollDiceEffect.DieRollResult> rolls) { var r__ = super.chooseRollToSwap(rolls); Probe.log(player, "chooseRollToSwap", new Object[]{rolls}, r__); return r__; }
    @Override public String chooseRollSwapValue(List<String> swapChoices, Integer currentResult, int power, int toughness) { var r__ = super.chooseRollSwapValue(swapChoices, currentResult, power, toughness); Probe.log(player, "chooseRollSwapValue", new Object[]{swapChoices, currentResult, power, toughness}, r__); return r__; }
    @Override public boolean mulliganKeepHand(Player firstPlayer, int cardsToReturn) { var r__ = super.mulliganKeepHand(firstPlayer, cardsToReturn); Probe.log(player, "mulliganKeepHand", new Object[]{firstPlayer, cardsToReturn}, r__); return r__; }
    @Override public CardCollectionView tuckCardsViaMulligan(CardCollectionView hand, int cardsToReturn) { var r__ = super.tuckCardsViaMulligan(hand, cardsToReturn); Probe.log(player, "tuckCardsViaMulligan", new Object[]{hand, cardsToReturn}, r__); return r__; }
    @Override public void declareAttackers(Player attacker, Combat combat) { super.declareAttackers(attacker, combat); Probe.log(player, "declareAttackers", new Object[]{attacker, combat}, null); }
    @Override public void declareBlockers(Player defender, Combat combat) { super.declareBlockers(defender, combat); Probe.log(player, "declareBlockers", new Object[]{defender, combat}, null); }
    @Override public List<SpellAbility> chooseSpellAbilityToPlay() { return super.chooseSpellAbilityToPlay(); }
    @Override public boolean playChosenSpellAbility(SpellAbility sa) { return super.playChosenSpellAbility(sa); }
    @Override public CardCollectionView chooseCardsToDiscardToMaximumHandSize(int numDiscard) { var r__ = super.chooseCardsToDiscardToMaximumHandSize(numDiscard); Probe.log(player, "chooseCardsToDiscardToMaximumHandSize", new Object[]{numDiscard}, r__); return r__; }
    @Override public CardCollectionView chooseCardsToRevealFromHand(int min, int max, CardCollectionView valid) { var r__ = super.chooseCardsToRevealFromHand(min, max, valid); Probe.log(player, "chooseCardsToRevealFromHand", new Object[]{min, max, valid}, r__); return r__; }
    @Override public Player chooseStartingPlayer(boolean isFirstGame) { var r__ = super.chooseStartingPlayer(isFirstGame); Probe.log(player, "chooseStartingPlayer", new Object[]{isFirstGame}, r__); return r__; }
    @Override public PlayerZone chooseStartingHand(List<PlayerZone> zones) { var r__ = super.chooseStartingHand(zones); Probe.log(player, "chooseStartingHand", new Object[]{zones}, r__); return r__; }
    @Override public List<SpellAbility> chooseSaToActivateFromOpeningHand(List<SpellAbility> usableFromOpeningHand) { var r__ = super.chooseSaToActivateFromOpeningHand(usableFromOpeningHand); Probe.log(player, "chooseSaToActivateFromOpeningHand", new Object[]{usableFromOpeningHand}, r__); return r__; }
    @Override public int chooseNumber(SpellAbility sa, String title, int min, int max) { var r__ = super.chooseNumber(sa, title, min, max); Probe.log(player, "chooseNumber", new Object[]{sa, title, min, max}, r__); return r__; }
    @Override public int chooseNumber(SpellAbility sa, String string, int min, int max, Map<String, Object> params) { var r__ = super.chooseNumber(sa, string, min, max, params); Probe.log(player, "chooseNumber", new Object[]{sa, string, min, max, params}, r__); return r__; }
    @Override public int chooseNumber(SpellAbility sa, String title, List<Integer> options, Player relatedPlayer) { var r__ = super.chooseNumber(sa, title, options, relatedPlayer); Probe.log(player, "chooseNumber", new Object[]{sa, title, options, relatedPlayer}, r__); return r__; }
    @Override public boolean chooseFlipResult(SpellAbility sa, Player flipper, boolean call) { var r__ = super.chooseFlipResult(sa, flipper, call); Probe.log(player, "chooseFlipResult", new Object[]{sa, flipper, call}, r__); return r__; }
    @Override public Pair<SpellAbilityStackInstance, GameObject> chooseTarget(SpellAbility saSrc, List<Pair<SpellAbilityStackInstance, GameObject>> allTargets) { var r__ = super.chooseTarget(saSrc, allTargets); Probe.log(player, "chooseTarget", new Object[]{saSrc, allTargets}, r__); return r__; }
    @Override public void notifyOfValue(SpellAbility saSource, GameObject realtedTarget, String value) { super.notifyOfValue(saSource, realtedTarget, value); Probe.log(player, "notifyOfValue", new Object[]{saSource, realtedTarget, value}, null); }
    @Override public boolean chooseBinary(SpellAbility sa, String question, BinaryChoiceType kindOfChoice, Boolean defaultVal) { var r__ = super.chooseBinary(sa, question, kindOfChoice, defaultVal); Probe.log(player, "chooseBinary", new Object[]{sa, question, kindOfChoice, defaultVal}, r__); return r__; }
    @Override public boolean chooseBinary(SpellAbility sa, String question, BinaryChoiceType kindOfChoice, Map<String, Object> params) { var r__ = super.chooseBinary(sa, question, kindOfChoice, params); Probe.log(player, "chooseBinary", new Object[]{sa, question, kindOfChoice, params}, r__); return r__; }
    @Override public List<AbilitySub> chooseModeForAbility(SpellAbility sa, List<AbilitySub> possible, int min, int num, boolean allowRepeat) { var r__ = super.chooseModeForAbility(sa, possible, min, num, allowRepeat); Probe.log(player, "chooseModeForAbility", new Object[]{sa, possible, min, num, allowRepeat}, r__); return r__; }
    @Override public byte chooseColorAllowColorless(String message, Card card, ColorSet colors) { var r__ = super.chooseColorAllowColorless(message, card, colors); Probe.log(player, "chooseColorAllowColorless", new Object[]{message, card, colors}, r__); return r__; }
    @Override public byte chooseColor(String message, SpellAbility sa, ColorSet colors) { var r__ = super.chooseColor(message, sa, colors); Probe.log(player, "chooseColor", new Object[]{message, sa, colors}, r__); return r__; }
    @Override public ColorSet chooseColors(String message, SpellAbility sa, int min, int max, ColorSet options) { var r__ = super.chooseColors(message, sa, min, max, options); Probe.log(player, "chooseColors", new Object[]{message, sa, min, max, options}, r__); return r__; }
    @Override public CounterType chooseCounterType(List<CounterType> options, SpellAbility sa, String prompt, Map<String, Object> params) { var r__ = super.chooseCounterType(options, sa, prompt, params); Probe.log(player, "chooseCounterType", new Object[]{options, sa, prompt, params}, r__); return r__; }
    @Override public String chooseKeywordForPump(List<String> options, SpellAbility sa, String prompt, Card tgtCard) { var r__ = super.chooseKeywordForPump(options, sa, prompt, tgtCard); Probe.log(player, "chooseKeywordForPump", new Object[]{options, sa, prompt, tgtCard}, r__); return r__; }
    @Override public ReplacementEffect chooseSingleReplacementEffect(List<ReplacementEffect> possibleReplacers) { var r__ = super.chooseSingleReplacementEffect(possibleReplacers); Probe.log(player, "chooseSingleReplacementEffect", new Object[]{possibleReplacers}, r__); return r__; }
    @Override public StaticAbility chooseSingleStaticAbility(List<StaticAbility> possibleStatics) { var r__ = super.chooseSingleStaticAbility(possibleStatics); Probe.log(player, "chooseSingleStaticAbility", new Object[]{possibleStatics}, r__); return r__; }
    @Override public String chooseProtectionType(SpellAbility sa, List<String> choices) { var r__ = super.chooseProtectionType(sa, choices); Probe.log(player, "chooseProtectionType", new Object[]{sa, choices}, r__); return r__; }
    @Override public boolean payManaCost(ManaCost toPay, CostPartMana costPartMana, SpellAbility sa, String prompt, ManaConversionMatrix matrix, boolean effect) { var r__ = super.payManaCost(toPay, costPartMana, sa, prompt, matrix, effect); Probe.log(player, "payManaCost", new Object[]{toPay, costPartMana, sa, prompt, matrix, effect}, r__); return r__; }
    @Override public boolean payCombatCost(Card c, Cost cost, SpellAbility sa, String prompt) { var r__ = super.payCombatCost(c, cost, sa, prompt); Probe.log(player, "payCombatCost", new Object[]{c, cost, sa, prompt}, r__); return r__; }
    @Override public CardCollectionView chooseCardsForCost(CardCollectionView optionList, SpellAbility sa, CostPartWithList cpl, int amount, boolean isOptional, String prompt) { var r__ = super.chooseCardsForCost(optionList, sa, cpl, amount, isOptional, prompt); Probe.log(player, "chooseCardsForCost", new Object[]{optionList, sa, cpl, amount, isOptional, prompt}, r__); return r__; }
    @Override public boolean applyManaToCost(ManaCostBeingPaid toPay, SpellAbility ability, String prompt, ManaConversionMatrix matrix, boolean effect) { var r__ = super.applyManaToCost(toPay, ability, prompt, matrix, effect); Probe.log(player, "applyManaToCost", new Object[]{toPay, ability, prompt, matrix, effect}, r__); return r__; }
    @Override public CostDecisionMakerBase getCostDecisionMaker(Player player, SpellAbility ability, boolean effect, String prompt) { return super.getCostDecisionMaker(player, ability, effect, prompt); }
    @Override public boolean payCostToPreventEffect(Cost cost, SpellAbility sa, boolean alreadyPaid, FCollectionView<Player> allPayers) { var r__ = super.payCostToPreventEffect(cost, sa, alreadyPaid, allPayers); Probe.log(player, "payCostToPreventEffect", new Object[]{cost, sa, alreadyPaid, allPayers}, r__); return r__; }
    @Override public boolean payCostDuringRoll(Cost cost, SpellAbility sa) { var r__ = super.payCostDuringRoll(cost, sa); Probe.log(player, "payCostDuringRoll", new Object[]{cost, sa}, r__); return r__; }
    @Override public List<SpellAbility> orderSimultaneousSa(List<SpellAbility> activePlayerSAs) { var r__ = super.orderSimultaneousSa(activePlayerSAs); Probe.log(player, "orderSimultaneousSa", new Object[]{activePlayerSAs}, r__); return r__; }
    @Override public void orderAndPlaySimultaneousSa(List<SpellAbility> activePlayerSAs) { super.orderAndPlaySimultaneousSa(activePlayerSAs); Probe.log(player, "orderAndPlaySimultaneousSa", new Object[]{activePlayerSAs}, null); }
    @Override public boolean playTrigger(Card host, WrappedAbility wrapperAbility, boolean isMandatory) { var r__ = super.playTrigger(host, wrapperAbility, isMandatory); Probe.log(player, "playTrigger", new Object[]{host, wrapperAbility, isMandatory}, r__); return r__; }
    @Override public boolean playSaFromPlayEffect(SpellAbility tgtSA) { var r__ = super.playSaFromPlayEffect(tgtSA); Probe.log(player, "playSaFromPlayEffect", new Object[]{tgtSA}, r__); return r__; }
    @Override public boolean chooseTargetsFor(SpellAbility currentAbility) { var r__ = super.chooseTargetsFor(currentAbility); Probe.log(player, "chooseTargetsFor", new Object[]{currentAbility}, r__); return r__; }
    @Override public TargetChoices chooseNewTargetsFor(SpellAbility ability, Predicate<GameObject> filter, boolean optional) { var r__ = super.chooseNewTargetsFor(ability, filter, optional); Probe.log(player, "chooseNewTargetsFor", new Object[]{ability, filter, optional}, r__); return r__; }
    @Override public boolean chooseCardsPile(SpellAbility sa, CardCollectionView pile1, CardCollectionView pile2, String faceUp) { var r__ = super.chooseCardsPile(sa, pile1, pile2, faceUp); Probe.log(player, "chooseCardsPile", new Object[]{sa, pile1, pile2, faceUp}, r__); return r__; }
    @Override public void revealAnte(String message, Multimap<Player, PaperCard> removedAnteCards) { super.revealAnte(message, removedAnteCards); Probe.log(player, "revealAnte", new Object[]{message, removedAnteCards}, null); }
    @Override public void revealAISkipCards(String message, Map<Player, Map<DeckSection, List<? extends PaperCard>>> deckCards) { super.revealAISkipCards(message, deckCards); Probe.log(player, "revealAISkipCards", new Object[]{message, deckCards}, null); }
    @Override public void revealUnsupported(Map<Player, List<PaperCard>> unsupported) { super.revealUnsupported(unsupported); Probe.log(player, "revealUnsupported", new Object[]{unsupported}, null); }
    @Override public Map<DeckSection, List<? extends PaperCard>> complainCardsCantPlayWell(Deck myDeck) { var r__ = super.complainCardsCantPlayWell(myDeck); Probe.log(player, "complainCardsCantPlayWell", new Object[]{myDeck}, r__); return r__; }
    @Override public CardCollectionView cheatShuffle(CardCollectionView list) { var r__ = super.cheatShuffle(list); Probe.log(player, "cheatShuffle", new Object[]{list}, r__); return r__; }
    @Override public List<PaperCard> chooseCardsYouWonToAddToDeck(List<PaperCard> losses) { var r__ = super.chooseCardsYouWonToAddToDeck(losses); Probe.log(player, "chooseCardsYouWonToAddToDeck", new Object[]{losses}, r__); return r__; }
    @Override public Map<Card, ManaCostShard> chooseCardsForConvokeOrImprovise(SpellAbility sa, ManaCost manaCost, CardCollectionView untappedCards, boolean artifacts, boolean creatures, Integer maxReduction) { var r__ = super.chooseCardsForConvokeOrImprovise(sa, manaCost, untappedCards, artifacts, creatures, maxReduction); Probe.log(player, "chooseCardsForConvokeOrImprovise", new Object[]{sa, manaCost, untappedCards, artifacts, creatures, maxReduction}, r__); return r__; }
    @Override public String chooseCardName(SpellAbility sa, List<ICardFace> faces, String message) { var r__ = super.chooseCardName(sa, faces, message); Probe.log(player, "chooseCardName", new Object[]{sa, faces, message}, r__); return r__; }
    @Override public String chooseCardName(SpellAbility sa, Predicate<ICardFace> cpp, String valid, String message) { var r__ = super.chooseCardName(sa, cpp, valid, message); Probe.log(player, "chooseCardName", new Object[]{sa, cpp, valid, message}, r__); return r__; }
    @Override public Card chooseSingleCardForZoneChange(ZoneType destination, List<ZoneType> origin, SpellAbility sa, CardCollection fetchList, DelayedReveal delayedReveal, String selectPrompt, boolean isOptional, Player decider) { var r__ = super.chooseSingleCardForZoneChange(destination, origin, sa, fetchList, delayedReveal, selectPrompt, isOptional, decider); Probe.log(player, "chooseSingleCardForZoneChange", new Object[]{destination, origin, sa, fetchList, delayedReveal, selectPrompt, isOptional, decider}, r__); return r__; }
    @Override public List<Card> chooseCardsForZoneChange(ZoneType destination, List<ZoneType> origin, SpellAbility sa, CardCollection fetchList, int min, int max, DelayedReveal delayedReveal, String selectPrompt, Player decider) { var r__ = super.chooseCardsForZoneChange(destination, origin, sa, fetchList, min, max, delayedReveal, selectPrompt, decider); Probe.log(player, "chooseCardsForZoneChange", new Object[]{destination, origin, sa, fetchList, min, max, delayedReveal, selectPrompt, decider}, r__); return r__; }
    @Override public void resetAtEndOfTurn() { super.resetAtEndOfTurn(); Probe.log(player, "resetAtEndOfTurn", new Object[]{}, null); }
    @Override public void autoPassCancel() { super.autoPassCancel(); Probe.log(player, "autoPassCancel", new Object[]{}, null); }
    @Override public void awaitNextInput() { super.awaitNextInput(); Probe.log(player, "awaitNextInput", new Object[]{}, null); }
    @Override public void cancelAwaitNextInput() { super.cancelAwaitNextInput(); }
    @Override public ICardFace chooseSingleCardFace(SpellAbility sa, List<ICardFace> faces, String message) { var r__ = super.chooseSingleCardFace(sa, faces, message); Probe.log(player, "chooseSingleCardFace", new Object[]{sa, faces, message}, r__); return r__; }
    @Override public ICardFace chooseSingleCardFace(SpellAbility sa, String message, Predicate<ICardFace> cpp, String name) { var r__ = super.chooseSingleCardFace(sa, message, cpp, name); Probe.log(player, "chooseSingleCardFace", new Object[]{sa, message, cpp, name}, r__); return r__; }
    @Override public CardState chooseSingleCardState(SpellAbility sa, List<CardState> states, String message, Map<String, Object> params) { var r__ = super.chooseSingleCardState(sa, states, message, params); Probe.log(player, "chooseSingleCardState", new Object[]{sa, states, message, params}, r__); return r__; }
    @Override public List<Card> chooseCardsForSplice(SpellAbility sa, List<Card> cards) { var r__ = super.chooseCardsForSplice(sa, cards); Probe.log(player, "chooseCardsForSplice", new Object[]{sa, cards}, r__); return r__; }
    @Override public List<OptionalCostValue> chooseOptionalCosts(SpellAbility chosen, List<OptionalCostValue> optionalCostValues) { var r__ = super.chooseOptionalCosts(chosen, optionalCostValues); Probe.log(player, "chooseOptionalCosts", new Object[]{chosen, optionalCostValues}, r__); return r__; }
    @Override public int chooseNumberForKeywordCost(SpellAbility sa, Cost cost, KeywordInterface keyword, String prompt, int max) { var r__ = super.chooseNumberForKeywordCost(sa, cost, keyword, prompt, max); Probe.log(player, "chooseNumberForKeywordCost", new Object[]{sa, cost, keyword, prompt, max}, r__); return r__; }
    @Override public int chooseNumberForCostReduction(SpellAbility sa, int min, int max) { var r__ = super.chooseNumberForCostReduction(sa, min, max); Probe.log(player, "chooseNumberForCostReduction", new Object[]{sa, min, max}, r__); return r__; }
    @Override public List<CostPart> orderCosts(List<CostPart> costs) { var r__ = super.orderCosts(costs); Probe.log(player, "orderCosts", new Object[]{costs}, r__); return r__; }
    @Override public CardCollection chooseCardsForEffectMultiple(Map<String, CardCollection> validMap, SpellAbility sa, String title, boolean isOptional) { var r__ = super.chooseCardsForEffectMultiple(validMap, sa, title, isOptional); Probe.log(player, "chooseCardsForEffectMultiple", new Object[]{validMap, sa, title, isOptional}, r__); return r__; }
}
